import type { Metadata } from 'next';
import { Toaster } from 'sonner';
import localFont from 'next/font/local';
import { Inter, Cormorant } from 'next/font/google';
import './globals.css';

const cinzel = localFont({
  src: '../public/fonts/CinzelVariable.ttf',
  variable: '--font-cinzel',
  display: 'swap',
  weight: '400 900',
});

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  weight: ['300', '400', '500'],
  display: 'swap',
});

const cormorant = Cormorant({
  subsets: ['latin'],
  variable: '--font-cormorant',
  weight: ['300', '400', '500', '600', '700'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${cinzel.variable} ${inter.variable} ${cormorant.variable} antialiased`}>
      <body>
        {children}
        <Toaster position="bottom-center" theme="light"></Toaster>
      </body>
    </html>
  );
}
